In [41]:
import pandas as pd

# Load the dataset
file_path = 'C:\\Users\\aravi\\OneDrive\\Desktop\\My Learning\\dataset\\Copper_Set.xlsx'
df = pd.read_excel(file_path)
df

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,20210401.0,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,20210401.0,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,0000000000000000000000000000000000104991,1668701718,20210401.0,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,20210401.0,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,20210101.0,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,20210401.0,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,20210401.0,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181668,DE633116-D1DF-4846-982E-55EFC3658A76,20200702.0,102.482422,30200854.0,25.0,Won,W,41.0,0.96,1220.0,0000000000000000000000000000000001000777,164141591,20200701.0,591.00
181669,A48374B1-E6DB-45F2-889A-1F9C27C099EB,20200702.0,208.086469,30200854.0,25.0,Won,W,41.0,0.95,1500.0,0000000000000000000000000000000001000227,164141591,20200701.0,589.00
181670,91643238-5C7B-4237-9A5F-63AE3D35F320,20200702.0,4.235594,30200854.0,25.0,Won,W,41.0,0.71,1250.0,0000000000000000000000000000000001004216,164141591,20200701.0,619.00
181671,7AFFD323-01D9-4E15-B80D-7D1B03498FC8,20200702.0,-2000,30200854.0,25.0,Won,W,41.0,0.85,1250.0,0000000000000000000000000000000001001149,164141591,20200701.0,601.00
181672,AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC,20200702.0,406.686538,30200854.0,25.0,Won,W,41.0,0.71,1240.0,0000000000000000000000000000000001005439,164141591,20200701.0,607.00

In [42]:
df.head()

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,20210401.0,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,20210401.0,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,0000000000000000000000000000000000104991,1668701718,20210401.0,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,20210401.0,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,20210101.0,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,20210401.0,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,20210401.0,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00

In [43]:
df.describe()

,item_date,customer,country,application,thickness,width,product_ref,delivery date,selling_price
count,1.816720e+05,1.816720e+05,181645.000000,181649.000000,181672.000000,181673.000000,1.816730e+05,1.816720e+05,1.816720e+05
mean,2.020459e+07,3.051221e+07,44.893022,25.615809,2.564827,1295.286724,4.739679e+08,2.020738e+07,1.918036e+03
std,4.551119e+03,2.433382e+07,24.404214,17.754175,6.572321,261.631754,7.175101e+08,2.411059e+04,3.317956e+05
min,1.995000e+07,1.245800e+04,25.000000,2.000000,0.180000,1.000000,6.117280e+05,2.019040e+07,-1.160000e+03
25%,2.020093e+07,3.019688e+07,26.000000,10.000000,0.700000,1180.000000,6.119930e+05,2.020110e+07,6.690000e+02
50%,2.020113e+07,3.020524e+07,30.000000,15.000000,1.500000,1250.000000,6.406650e+05,2.021010e+07,8.120000e+02
75%,2.021020e+07,3.028042e+07,78.000000,41.000000,3.000000,1500.000000,1.332077e+09,2.021040e+07,9.530000e+02
max,2.021040e+07,2.147484e+09,113.000000,99.000000,2500.000000,2990.000000,1.722208e+09,3.031010e+07,1.000010e+08

In [44]:
df.isnull().sum()

id                   2
item_date            1
quantity tons        0
customer             1
country             28
status               2
item type            0
application         24
thickness            1
width                0
material_ref     77919
product_ref          0
delivery date        1
selling_price        1
dtype: int64

In [45]:
#Check the distribution of the target variables
df['selling_price'].describe()

count    1.816720e+05
mean     1.918036e+03
std      3.317956e+05
min     -1.160000e+03
25%      6.690000e+02
50%      8.120000e+02
75%      9.530000e+02
max      1.000010e+08
Name: selling_price, dtype: float64

In [46]:
df['status'].value_counts()

status
Won                116010
Lost                34438
Not lost for AM     19573
Revised              4276
To be approved       4170
Draft                3140
Offered                53
Offerable              10
Wonderful               1
Name: count, dtype: int64

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181673 entries, 0 to 181672
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             181671 non-null  object
 1   item_date      181672 non-null  float64
 2   quantity tons  181673 non-null  object
 3   customer       181672 non-null  float64
 4   country        181645 non-null  float64
 5   status         181671 non-null  object
 6   item type      181673 non-null  object
 7   application    181649 non-null  float64
 8   thickness      181672 non-null  float64
 9   width          181673 non-null  float64
 10  material_ref   103754 non-null  object
 11  product_ref    181673 non-null  int64
 12  delivery date  181672 non-null  float64
 13  selling_price  181672 non-null  float64
dtypes: float64(8), int64(1), object(5)
memory usage: 19.4+ MB

In [48]:
df = df.dropna()

In [49]:
df

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,20210401.0,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,20210401.0,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,0000000000000000000000000000000000104991,1668701718,20210401.0,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,20210401.0,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,20210101.0,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,20210401.0,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,20210401.0,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181668,DE633116-D1DF-4846-982E-55EFC3658A76,20200702.0,102.482422,30200854.0,25.0,Won,W,41.0,0.96,1220.0,0000000000000000000000000000000001000777,164141591,20200701.0,591.00
181669,A48374B1-E6DB-45F2-889A-1F9C27C099EB,20200702.0,208.086469,30200854.0,25.0,Won,W,41.0,0.95,1500.0,0000000000000000000000000000000001000227,164141591,20200701.0,589.00
181670,91643238-5C7B-4237-9A5F-63AE3D35F320,20200702.0,4.235594,30200854.0,25.0,Won,W,41.0,0.71,1250.0,0000000000000000000000000000000001004216,164141591,20200701.0,619.00
181671,7AFFD323-01D9-4E15-B80D-7D1B03498FC8,20200702.0,-2000,30200854.0,25.0,Won,W,41.0,0.85,1250.0,0000000000000000000000000000000001001149,164141591,20200701.0,601.00
181672,AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC,20200702.0,406.686538,30200854.0,25.0,Won,W,41.0,0.71,1240.0,0000000000000000000000000000000001005439,164141591,20200701.0,607.00

In [50]:
# Filter to keep only 'Won' and 'Lost' statuses
filtered_df = df[df['status'].isin(['Won', 'Lost'])]

# Optionally, you can overwrite the original df with the filtered data
df = filtered_df

In [51]:
df

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,20210401.0,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,20210401.0,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,0000000000000000000000000000000000104991,1668701718,20210401.0,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,20210401.0,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,20210101.0,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,20210401.0,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,20210401.0,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181668,DE633116-D1DF-4846-982E-55EFC3658A76,20200702.0,102.482422,30200854.0,25.0,Won,W,41.0,0.96,1220.0,0000000000000000000000000000000001000777,164141591,20200701.0,591.00
181669,A48374B1-E6DB-45F2-889A-1F9C27C099EB,20200702.0,208.086469,30200854.0,25.0,Won,W,41.0,0.95,1500.0,0000000000000000000000000000000001000227,164141591,20200701.0,589.00
181670,91643238-5C7B-4237-9A5F-63AE3D35F320,20200702.0,4.235594,30200854.0,25.0,Won,W,41.0,0.71,1250.0,0000000000000000000000000000000001004216,164141591,20200701.0,619.00
181671,7AFFD323-01D9-4E15-B80D-7D1B03498FC8,20200702.0,-2000,30200854.0,25.0,Won,W,41.0,0.85,1250.0,0000000000000000000000000000000001001149,164141591,20200701.0,601.00
181672,AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC,20200702.0,406.686538,30200854.0,25.0,Won,W,41.0,0.71,1240.0,0000000000000000000000000000000001005439,164141591,20200701.0,607.00

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87648 entries, 0 to 181672
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             87648 non-null  object
 1   item_date      87648 non-null  float64
 2   quantity tons  87648 non-null  object
 3   customer       87648 non-null  float64
 4   country        87648 non-null  float64
 5   status         87648 non-null  object
 6   item type      87648 non-null  object
 7   application    87648 non-null  float64
 8   thickness      87648 non-null  float64
 9   width          87648 non-null  float64
 10  material_ref   87648 non-null  object
 11  product_ref    87648 non-null  int64
 12  delivery date  87648 non-null  float64
 13  selling_price  87648 non-null  float64
dtypes: float64(8), int64(1), object(5)
memory usage: 10.0+ MB

In [53]:
df.dtypes

id                object
item_date        float64
quantity tons     object
customer         float64
country          float64
status            object
item type         object
application      float64
thickness        float64
width            float64
material_ref      object
product_ref        int64
delivery date    float64
selling_price    float64
dtype: object

In [54]:
file_name = 'CopperSet.xlsx'
df.to_excel(file_name)
print(f"DataFrame saved to '{file_name}' successfully.")

DataFrame saved to 'CopperSet.xlsx' successfully.

In [55]:

# Convert 'item_date' and 'delivery_date' to datetime
df['item_date'] = pd.to_datetime(df['item_date'], errors='coerce')
df['delivery date'] = pd.to_datetime(df['delivery date'], errors='coerce')

# Convert 'quantity tons' to numeric (assuming it should be a float)
df['quantity tons'] = pd.to_numeric(df['quantity tons'], errors='coerce')

# Convert 'customer', 'country', and 'application' to numeric (assuming they should be integers or floats)
df['customer'] = pd.to_numeric(df['customer'], errors='coerce')
df['country'] = pd.to_numeric(df['country'], errors='coerce')
df['application'] = pd.to_numeric(df['application'], errors='coerce')

# Convert 'thickness' and 'width' to numeric (assuming they should be floats)
df['thickness'] = pd.to_numeric(df['thickness'], errors='coerce')
df['width'] = pd.to_numeric(df['width'], errors='coerce')

# Convert 'product_ref' to integer
df['product_ref'] = df['product_ref'].astype(int)

C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\2759523654.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['item_date'] = pd.to_datetime(df['item_date'], errors='coerce')
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\2759523654.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['delivery date'] = pd.to_datetime(df['delivery date'], errors='coerce')
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\2759523654.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['quantity tons'] = pd.to_numeric(df['quantity tons'], errors='coerce')
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\2759523654.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer'] = pd.to_numeric(df['customer'], errors='coerce')
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\2759523654.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'] = pd.to_numeric(df['country'], errors='coerce')
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\2759523654.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['application'] = pd.to_numeric(df['application'], errors='coerce')
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\2759523654.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['thickness'] = pd.to_numeric(df['thickness'], errors='coerce')
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\2759523654.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['width'] = pd.to_numeric(df['width'], errors='coerce')
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\2759523654.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['product_ref'] = df['product_ref'].astype(int)

In [56]:
df.dtypes

id                       object
item_date        datetime64[ns]
quantity tons           float64
customer                float64
country                 float64
status                   object
item type                object
application             float64
thickness               float64
width                   float64
material_ref             object
product_ref               int32
delivery date    datetime64[ns]
selling_price           float64
dtype: object

In [57]:
file_name = 'Copperdataset.xlsx'
df.to_excel(file_name)
print(f"DataFrame saved to '{file_name}' successfully.")

DataFrame saved to 'Copperdataset.xlsx' successfully.

In [58]:
df

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,1970-01-01 00:00:00.020210401,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,1970-01-01 00:00:00.020210701,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,1970-01-01 00:00:00.020210401,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,0000000000000000000000000000000000104991,1668701718,1970-01-01 00:00:00.020210401,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,1970-01-01 00:00:00.020210401,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,1970-01-01 00:00:00.020210101,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,1970-01-01 00:00:00.020210401,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,1970-01-01 00:00:00.020210101,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,1970-01-01 00:00:00.020210401,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,1970-01-01 00:00:00.020210301,577.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181668,DE633116-D1DF-4846-982E-55EFC3658A76,1970-01-01 00:00:00.020200702,102.482422,30200854.0,25.0,Won,W,41.0,0.96,1220.0,0000000000000000000000000000000001000777,164141591,1970-01-01 00:00:00.020200701,591.00
181669,A48374B1-E6DB-45F2-889A-1F9C27C099EB,1970-01-01 00:00:00.020200702,208.086469,30200854.0,25.0,Won,W,41.0,0.95,1500.0,0000000000000000000000000000000001000227,164141591,1970-01-01 00:00:00.020200701,589.00
181670,91643238-5C7B-4237-9A5F-63AE3D35F320,1970-01-01 00:00:00.020200702,4.235594,30200854.0,25.0,Won,W,41.0,0.71,1250.0,0000000000000000000000000000000001004216,164141591,1970-01-01 00:00:00.020200701,619.00
181671,7AFFD323-01D9-4E15-B80D-7D1B03498FC8,1970-01-01 00:00:00.020200702,-2000.000000,30200854.0,25.0,Won,W,41.0,0.85,1250.0,0000000000000000000000000000000001001149,164141591,1970-01-01 00:00:00.020200701,601.00
181672,AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC,1970-01-01 00:00:00.020200702,406.686538,30200854.0,25.0,Won,W,41.0,0.71,1240.0,0000000000000000000000000000000001005439,164141591,1970-01-01 00:00:00.020200701,607.00

In [59]:
import numpy as np

df1 = df.drop(columns=['id'])
df1['material_ref'] = df1['material_ref'].apply(lambda x: np.nan if str(x).startswith('00000') else x)

In [60]:
df1.head()

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,1970-01-01 00:00:00.020210401,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,1970-01-01 00:00:00.020210701,854.00
1,1970-01-01 00:00:00.020210401,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,NaN,1668701718,1970-01-01 00:00:00.020210401,1047.00
2,1970-01-01 00:00:00.020210401,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,1970-01-01 00:00:00.020210101,644.33
3,1970-01-01 00:00:00.020210401,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,1970-01-01 00:00:00.020210101,768.00
4,1970-01-01 00:00:00.020210401,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,1970-01-01 00:00:00.020210301,577.00

In [61]:
df1

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,1970-01-01 00:00:00.020210401,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,1970-01-01 00:00:00.020210701,854.00
1,1970-01-01 00:00:00.020210401,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,NaN,1668701718,1970-01-01 00:00:00.020210401,1047.00
2,1970-01-01 00:00:00.020210401,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,1970-01-01 00:00:00.020210101,644.33
3,1970-01-01 00:00:00.020210401,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,1970-01-01 00:00:00.020210101,768.00
4,1970-01-01 00:00:00.020210401,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,1970-01-01 00:00:00.020210301,577.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
181668,1970-01-01 00:00:00.020200702,102.482422,30200854.0,25.0,Won,W,41.0,0.96,1220.0,NaN,164141591,1970-01-01 00:00:00.020200701,591.00
181669,1970-01-01 00:00:00.020200702,208.086469,30200854.0,25.0,Won,W,41.0,0.95,1500.0,NaN,164141591,1970-01-01 00:00:00.020200701,589.00
181670,1970-01-01 00:00:00.020200702,4.235594,30200854.0,25.0,Won,W,41.0,0.71,1250.0,NaN,164141591,1970-01-01 00:00:00.020200701,619.00
181671,1970-01-01 00:00:00.020200702,-2000.000000,30200854.0,25.0,Won,W,41.0,0.85,1250.0,NaN,164141591,1970-01-01 00:00:00.020200701,601.00
181672,1970-01-01 00:00:00.020200702,406.686538,30200854.0,25.0,Won,W,41.0,0.71,1240.0,NaN,164141591,1970-01-01 00:00:00.020200701,607.00

In [62]:
df1 = df1.dropna()

In [63]:
df1

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,1970-01-01 00:00:00.020210401,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,1970-01-01 00:00:00.020210701,854.00
2,1970-01-01 00:00:00.020210401,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,1970-01-01 00:00:00.020210101,644.33
3,1970-01-01 00:00:00.020210401,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,1970-01-01 00:00:00.020210101,768.00
4,1970-01-01 00:00:00.020210401,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,1970-01-01 00:00:00.020210301,577.00
13,1970-01-01 00:00:00.020210401,32.235317,30202362.0,27.0,Won,S,10.0,0.60,1010.0,DC04EK,628377,1970-01-01 00:00:00.020210701,973.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
181569,1970-01-01 00:00:00.020200702,14.247148,30201866.0,32.0,Won,W,41.0,0.58,1220.0,7016/17/1220/0.60,611993,1970-01-01 00:00:00.020200701,816.00
181571,1970-01-01 00:00:00.020200702,17.748421,30201866.0,32.0,Won,W,41.0,0.50,1250.0,8012/17/1250/0.50,611993,1970-01-01 00:00:00.020200701,817.00
181573,1970-01-01 00:00:00.020200702,16.692213,30201866.0,32.0,Won,W,41.0,0.50,1250.0,7016/17/1250/0.50,611993,1970-01-01 00:00:00.020200701,811.00
181575,1970-01-01 00:00:00.020200702,13.728952,30201866.0,32.0,Won,W,41.0,0.50,996.0,6011/17/996/0.50,611993,1970-01-01 00:00:00.020200701,812.00
181605,1970-01-01 00:00:00.020200702,34.426799,30201369.0,25.0,Won,S,41.0,0.60,1288.0,202006170005.IO.1.1,611993,1970-01-01 00:00:00.020200701,981.00

In [64]:
df1.dtypes

item_date        datetime64[ns]
quantity tons           float64
customer                float64
country                 float64
status                   object
item type                object
application             float64
thickness               float64
width                   float64
material_ref             object
product_ref               int32
delivery date    datetime64[ns]
selling_price           float64
dtype: object

In [65]:
df1.head()

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,1970-01-01 00:00:00.020210401,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,1970-01-01 00:00:00.020210701,854.00
2,1970-01-01 00:00:00.020210401,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,1970-01-01 00:00:00.020210101,644.33
3,1970-01-01 00:00:00.020210401,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,1970-01-01 00:00:00.020210101,768.00
4,1970-01-01 00:00:00.020210401,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,1970-01-01 00:00:00.020210301,577.00
13,1970-01-01 00:00:00.020210401,32.235317,30202362.0,27.0,Won,S,10.0,0.60,1010.0,DC04EK,628377,1970-01-01 00:00:00.020210701,973.00

In [66]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 68029 entries, 0 to 181605
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item_date      68029 non-null  datetime64[ns]
 1   quantity tons  68029 non-null  float64
 2   customer       68029 non-null  float64
 3   country        68029 non-null  float64
 4   status         68029 non-null  object
 5   item type      68029 non-null  object
 6   application    68029 non-null  float64
 7   thickness      68029 non-null  float64
 8   width          68029 non-null  float64
 9   material_ref   68029 non-null  object
 10  product_ref    68029 non-null  int32
 11  delivery date  68029 non-null  datetime64[ns]
 12  selling_price  68029 non-null  float64
dtypes: datetime64[ns](2), float64(7), int32(1), object(3)
memory usage: 7.0+ MB

In [69]:
import numpy as np
from sklearn.ensemble import IsolationForest
# Convert relevant columns to numeric data types
numeric_cols = ['quantity tons', 'application', 'thickness', 'width', 'selling_price']
df1[numeric_cols] = df1[numeric_cols].apply(pd.to_numeric, errors='coerce')

# Drop rows with NaN values after conversion
df1.dropna(subset=numeric_cols, inplace=True)

# Calculate IQR for each numerical column
Q1 = df1[numeric_cols].quantile(0.25)
Q3 = df1[numeric_cols].quantile(0.75)
IQR = Q3 - Q1

# Define a function to treat outliers using IQR
def treat_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df[column] = df[column].clip(lower_bound, upper_bound)
    return df

# Apply the function to treat outliers for each numerical column
for col in numeric_cols:
    df1 = treat_outliers_iqr(df1, col)

# Alternatively, you can use Isolation Forest for outlier detection
iso_forest = IsolationForest(contamination=0.05)  # Adjust contamination as needed
outlier_mask = iso_forest.fit_predict(df1[numeric_cols])
df1 = df1[outlier_mask == 1]  # Keep non-outliers

# Print the updated DataFrame
print(df1)

C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\3260234324.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[numeric_cols] = df1[numeric_cols].apply(pd.to_numeric, errors='coerce')
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\3260234324.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.dropna(subset=numeric_cols, inplace=True)
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\3260234324.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = df[column].clip(lower_bound, upper_bound)
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\3260234324.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = df[column].clip(lower_bound, upper_bound)
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\3260234324.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = df[column].clip(lower_bound, upper_bound)
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\3260234324.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = df[column].clip(lower_bound, upper_bound)
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\3260234324.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = df[column].clip(lower_bound, upper_bound)
C:\Users\aravi\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

                           item_date  quantity tons    customer  country  \
0      1970-01-01 00:00:00.020210401      54.151139  30156308.0     28.0
2      1970-01-01 00:00:00.020210401     165.335628  30153963.0     30.0
3      1970-01-01 00:00:00.020210401     165.335628  30349574.0     32.0
13     1970-01-01 00:00:00.020210401      32.235317  30202362.0     27.0
16     1970-01-01 00:00:00.020210401      75.124394  30153510.0     30.0
...                              ...            ...         ...      ...
181569 1970-01-01 00:00:00.020200702      14.247148  30201866.0     32.0
181571 1970-01-01 00:00:00.020200702      17.748421  30201866.0     32.0
181573 1970-01-01 00:00:00.020200702      16.692213  30201866.0     32.0
181575 1970-01-01 00:00:00.020200702      13.728952  30201866.0     32.0
181605 1970-01-01 00:00:00.020200702      34.426799  30201369.0     25.0

       status item type  application  thickness   width  \
0         Won         W         10.0      2.000  1500.0
2         Won        WI         28.0      0.380   952.0
3         Won         S         59.0      2.300  1317.0
13        Won         S         10.0      0.600  1010.0
16        Won         W         41.0      0.595  1265.0
...       ...       ...          ...        ...     ...
181569    Won         W         41.0      0.580  1220.0
181571    Won         W         41.0      0.500  1250.0
181573    Won         W         41.0      0.500  1250.0
181575    Won         W         41.0      0.500   996.0
181605    Won         S         41.0      0.600  1288.0

                   material_ref  product_ref                 delivery date  \
0                   DEQ1 S460MC   1670798778 1970-01-01 00:00:00.020210701
2                      S0380700       628377 1970-01-01 00:00:00.020210101
3       DX51D+ZM310MAO 2.3X1317   1668701718 1970-01-01 00:00:00.020210101
13                       DC04EK       628377 1970-01-01 00:00:00.020210701
16                PEA1265X595SP       611993 1970-01-01 00:00:00.020210401
...                         ...          ...                           ...
181569        7016/17/1220/0.60       611993 1970-01-01 00:00:00.020200701
181571        8012/17/1250/0.50       611993 1970-01-01 00:00:00.020200701
181573        7016/17/1250/0.50       611993 1970-01-01 00:00:00.020200701
181575         6011/17/996/0.50       611993 1970-01-01 00:00:00.020200701
181605      202006170005.IO.1.1       611993 1970-01-01 00:00:00.020200701

        selling_price
0              854.00
2              644.33
3              768.00
13             973.00
16            1161.86
...               ...
181569         816.00
181571         817.00
181573         811.00
181575         812.00
181605         981.00

[64627 rows x 13 columns]

In [71]:
df1.head()

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,1970-01-01 00:00:00.020210401,54.151139,30156308.0,28.0,Won,W,10.0,2.000,1500.0,DEQ1 S460MC,1670798778,1970-01-01 00:00:00.020210701,854.00
2,1970-01-01 00:00:00.020210401,165.335628,30153963.0,30.0,Won,WI,28.0,0.380,952.0,S0380700,628377,1970-01-01 00:00:00.020210101,644.33
3,1970-01-01 00:00:00.020210401,165.335628,30349574.0,32.0,Won,S,59.0,2.300,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,1970-01-01 00:00:00.020210101,768.00
13,1970-01-01 00:00:00.020210401,32.235317,30202362.0,27.0,Won,S,10.0,0.600,1010.0,DC04EK,628377,1970-01-01 00:00:00.020210701,973.00
16,1970-01-01 00:00:00.020210401,75.124394,30153510.0,30.0,Won,W,41.0,0.595,1265.0,PEA1265X595SP,611993,1970-01-01 00:00:00.020210401,1161.86

In [73]:
file_name = 'Copperdata.xlsx'
df1.to_excel(file_name)
print(f"DataFrame saved to '{file_name}' successfully.")

DataFrame saved to 'Copperdata.xlsx' successfully.

In [76]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Encoding categorical columns: 'status', 'item type', 'material_ref'
label_encoders = {}
for column in ['status', 'item type', 'material_ref']:
    le = LabelEncoder()
    df1[column] = le.fit_transform(df1[column])
    label_encoders[column] = le

# Splitting the data into features and target variables
X = df1.drop(columns=['selling_price', 'status'])
y_regression = df1['selling_price']  # Target for regression
y_classification = df1['status']     # Target for classification

# Splitting the data into training and testing sets
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X, y_regression, test_size=0.2, random_state=42)
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X, y_classification, test_size=0.2, random_state=42)

X_train_reg.head(), X_test_reg.head(), y_train_reg.head(), y_test_reg.head()

C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\3046117460.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[column] = le.fit_transform(df1[column])
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\3046117460.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[column] = le.fit_transform(df1[column])
C:\Users\aravi\AppData\Local\Temp\ipykernel_5100\3046117460.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[column] = le.fit_transform(df1[column])

(                           item_date  quantity tons    customer  country  \
 57089  1970-01-01 00:00:00.020210120      59.108171  30203366.0     28.0
 86605  1970-01-01 00:00:00.020201203     106.563766  30164695.0     27.0
 49146  1970-01-01 00:00:00.020210129       2.001354  30205312.0     32.0
 78644  1970-01-01 00:00:00.020201211      17.889932  30201866.0     32.0
 140995 1970-01-01 00:00:00.020200921       3.917328  30280416.0     28.0

         item type  application  thickness   width  material_ref  product_ref  \
 57089           3         10.0        5.0  1995.0          4461       640665
 86605           2         10.0        2.5  1500.0          3686   1670798778
 49146           4         10.0        3.0  1100.0          9260       640665
 78644           4         41.0        0.5   996.0          2432       611993
 140995          4         15.0        0.6  1250.0          8015       611993

                        delivery date
 57089  1970-01-01 00:00:00.020210401
 86605  1970-01-01 00:00:00.020210201
 49146  1970-01-01 00:00:00.020210501
 78644  1970-01-01 00:00:00.020210101
 140995 1970-01-01 00:00:00.020200701  ,
                            item_date  quantity tons    customer  country  \
 110521 1970-01-01 00:00:00.020201103       8.257095  30218904.0     78.0
 30946  1970-01-01 00:00:00.020210226      85.527664  30346534.0     32.0
 139511 1970-01-01 00:00:00.020200922      22.061593  30235584.0     27.0
 113410 1970-01-01 00:00:00.020201028      14.710985  30160378.0     78.0
 29814  1970-01-01 00:00:00.020210301      32.246410  30202361.0     27.0

         item type  application  thickness   width  material_ref  product_ref  \
 110521          4         10.0        0.5  1250.0          6060       611993
 30946           4         59.0        6.1  1375.0          6603       640665
 139511          3         41.0        0.3  1100.0          3405       611993
 113410          4         41.0        1.0  1248.0          6085       611993
 29814           3         10.0        6.0  1500.0          3744       640665

                        delivery date
 110521 1970-01-01 00:00:00.020201201
 30946  1970-01-01 00:00:00.020210501
 139511 1970-01-01 00:00:00.020201001
 113410 1970-01-01 00:00:00.020201201
 29814  1970-01-01 00:00:00.020210501  ,
 57089     839.00
 86605     628.54
 49146     817.00
 78644     944.00
 140995    777.00
 Name: selling_price, dtype: float64,
 110521    931.0
 30946     782.0
 139511    947.0
 113410    802.0
 29814     812.0
 Name: selling_price, dtype: float64)

In [77]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Assuming X_train_reg, X_test_reg, y_train_reg, and y_test_reg have been defined

# Extracting year, month, and day from 'item_date' and 'delivery date'
for date_col in ['item_date', 'delivery date']:
    X_train_reg[date_col + '_year'] = X_train_reg[date_col].dt.year
    X_train_reg[date_col + '_month'] = X_train_reg[date_col].dt.month
    X_train_reg[date_col + '_day'] = X_train_reg[date_col].dt.day
    X_test_reg[date_col + '_year'] = X_test_reg[date_col].dt.year
    X_test_reg[date_col + '_month'] = X_test_reg[date_col].dt.month
    X_test_reg[date_col + '_day'] = X_test_reg[date_col].dt.day

# Dropping the original datetime columns
X_train_reg.drop(columns=['item_date', 'delivery date'], inplace=True)
X_test_reg.drop(columns=['item_date', 'delivery date'], inplace=True)

# Train the Linear Regression model
reg_model = LinearRegression()
reg_model.fit(X_train_reg, y_train_reg)

# Predict on the test set
y_pred_reg = reg_model.predict(X_test_reg)

# Evaluate the regression model
mse_reg = mean_squared_error(y_test_reg, y_pred_reg)
r2_reg = r2_score(y_test_reg, y_pred_reg)

print("Mean Squared Error:", mse_reg)
print("R-squared:", r2_reg)

Mean Squared Error: 30077.60062488951
R-squared: 0.1887872872043811

In [78]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Assuming X_train_clf, X_test_clf, y_train_clf, and y_test_clf have been defined

# Extracting year, month, and day from 'item_date' and 'delivery date'
for date_col in ['item_date', 'delivery date']:
    X_train_clf[date_col + '_year'] = X_train_clf[date_col].dt.year
    X_train_clf[date_col + '_month'] = X_train_clf[date_col].dt.month
    X_train_clf[date_col + '_day'] = X_train_clf[date_col].dt.day
    X_test_clf[date_col + '_year'] = X_test_clf[date_col].dt.year
    X_test_clf[date_col + '_month'] = X_test_clf[date_col].dt.month
    X_test_clf[date_col + '_day'] = X_test_clf[date_col].dt.day

# Dropping the original datetime columns
X_train_clf.drop(columns=['item_date', 'delivery date'], inplace=True)
X_test_clf.drop(columns=['item_date', 'delivery date'], inplace=True)

# Train the Logistic Regression model
clf_model = LogisticRegression(max_iter=1000)
clf_model.fit(X_train_clf, y_train_clf)

# Predict on the test set
y_pred_clf = clf_model.predict(X_test_clf)

# Evaluate the classification model
accuracy_clf = accuracy_score(y_test_clf, y_pred_clf)
classification_rep = classification_report(y_test_clf, y_pred_clf)

print("Accuracy:", accuracy_clf)
print("Classification Report:\n", classification_rep)

Accuracy: 0.8725823920779824
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00      1647
           1       0.87      1.00      0.93     11279

    accuracy                           0.87     12926
   macro avg       0.44      0.50      0.47     12926
weighted avg       0.76      0.87      0.81     12926

C:\Users\aravi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\aravi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\aravi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
import pandas as pd
import streamlit as st
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, classification_report
import joblib




label_encoders = {}
for column in ['status', 'item type', 'material_ref']:
    le = LabelEncoder()
    df1[column] = le.fit_transform(df1[column])
    label_encoders[column] = le

# Splitting the data into features and target variables
X = df1.drop(columns=['selling_price', 'status'])
y_regression = df1['selling_price']  # Target for regression
y_classification = df1['status']     # Target for classification

# Splitting the data into training and testing sets
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X, y_regression, test_size=0.2, random_state=42)
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X, y_classification, test_size=0.2, random_state=42)

X_train_reg.head(), X_test_reg.head(), y_train_reg.head(), y_test_reg.head()

#Regression
# Assuming X_train_reg, X_test_reg, y_train_reg, and y_test_reg have been defined
# Extracting year, month, and day from 'item_date' and 'delivery date'
for date_col in ['item_date', 'delivery date']:
    X_train_reg[date_col + '_year'] = X_train_reg[date_col].dt.year
    X_train_reg[date_col + '_month'] = X_train_reg[date_col].dt.month
    X_train_reg[date_col + '_day'] = X_train_reg[date_col].dt.day
    X_test_reg[date_col + '_year'] = X_test_reg[date_col].dt.year
    X_test_reg[date_col + '_month'] = X_test_reg[date_col].dt.month
    X_test_reg[date_col + '_day'] = X_test_reg[date_col].dt.day

# Dropping the original datetime columns
X_train_reg.drop(columns=['item_date', 'delivery date'], inplace=True)
X_test_reg.drop(columns=['item_date', 'delivery date'], inplace=True)
X_train_clf.drop(columns=['item_date', 'delivery date'], inplace=True)
X_test_clf.drop(columns=['item_date', 'delivery date'], inplace=True)

# Train the Linear Regression model
reg_model = LinearRegression()
reg_model.fit(X_train_reg, y_train_reg)

# Train the Logistic Regression model
clf_model = LogisticRegression(max_iter=1000)
clf_model.fit(X_train_clf, y_train_clf)

# Save the models and label encoders
joblib.dump(reg_model, 'reg_model.pkl')
joblib.dump(clf_model, 'clf_model.pkl')
joblib.dump(label_encoders, 'label_encoders.pkl')

print("Models and label encoders have been saved.")

reg_model = joblib.load('reg_model.pkl')
clf_model = joblib.load('clf_model.pkl')
label_encoders = joblib.load('label_encoders.pkl')

st.title("Selling Price and Status Prediction")

# Collect user inputs
quantity_tons = st.number_input("Quantity (tons)", min_value=0.0)
customer = st.number_input("Customer ID", min_value=0)
country = st.number_input("Country Code", min_value=0)
item_type = st.selectbox("Item Type", label_encoders['item type'].classes_)  # Use label encoder mapping
application = st.number_input("Application Code", min_value=0)
thickness = st.number_input("Thickness", min_value=0.0)
width = st.number_input("Width", min_value=0.0)
material_ref = st.selectbox("Material Reference", label_encoders['material_ref'].classes_)  # Use label encoder mapping
product_ref = st.number_input("Product Reference", min_value=0)
item_date = st.date_input("Item Date")
delivery_date = st.date_input("Delivery Date")

# Convert dates to numeric features
item_date_year = item_date.year
item_date_month = item_date.month
item_date_day = item_date.day
delivery_date_year = delivery_date.year
delivery_date_month = delivery_date.month
delivery_date_day = delivery_date.day

# Prepare the input data
input_data = pd.DataFrame({
    'quantity tons': [quantity_tons],
    'customer': [customer],
    'country': [country],
    'item type': [label_encoders['item type'].transform([item_type])[0]],
    'application': [application],
    'thickness': [thickness],
    'width': [width],
    'material_ref': [label_encoders['material_ref'].transform([material_ref])[0]],
    'product_ref': [product_ref],
    'item_date_year': [item_date_year],
    'item_date_month': [item_date_month],
    'item_date_day': [item_date_day],
    'delivery_date_year': [delivery_date_year],
    'delivery_date_month': [delivery_date_month],
    'delivery_date_day': [delivery_date_day]
})

# Predict Selling Price
predicted_price = reg_model.predict(input_data)
st.write(f"Predicted Selling Price: {predicted_price[0]}")

# Predict Status
predicted_status = clf_model.predict(input_data)
predicted_status_label = label_encoders['status'].inverse_transform(predicted_status)
st.write(f"Predicted Status: {predicted_status_label[0]}")